spring.application.name=deepseek
# DeepSeek API Configuration
#deepseek.api.key=sk-84a049186cd34c71adbb149d9dd97402
deepseek.api.url=https://api.deepseek.com/v1/chat/completions
deepseek.api.model=deepseek-chat